### ISSUE TITLE
ts-loader with typescript 1.6 and tsx

### ISSUE THREAD

**Issue by dhruvp** [jbrantly/ts-loader#39]
I've been trying to use ts-loader with tsx files that have jsx in them. Unfortunately, webpack always throws this error: 

ERROR in ./app/index.tsx
Module build failed: error TS5012: Cannot read file '/Users/me/Documents/engineering/project/tsconfig.json': undefined is not a function

I don't think this is a problem with my tsconfig.json because it works fine with tsc from the command line and the gulp-typescript module. Any help here would be much appreciated as this is the only thing keeping me from using this loader!

**Comment by dhruvp** [comment]
for reference, this is my tsconfig:
```
{
    "compilerOptions": {
        "target": "ES5",
        "jsx": "react",
        "module": "umd"
    },
    "files": [
        "typings/tsd.d.ts"
    ]
}
```

**Comment by jbrantly** [comment]
This was due to a recent issue with the TypeScript nightly that was a breaking change. See Microsoft/TypeScript#4497

I hadn't planned on fixing it because they were going to fix the breaking change part, but as you're the second person who's mentioned this and since I have no idea when they're going to fix the breaking change I've went ahead and published a new version. Please try v0.5.4.

**Comment by dhruvp** [comment]
thank you! It worked like a charm. You're the best
