### ISSUE TITLE
Failing to resolve TypeScript library via NPM

### ISSUE THREAD

**Issue by SonofNun15** [jbrantly/ts-loader#46]
I created a small sample library with a readme detailing the problem. `ts-loader` appears to have trouble finding a typescript module in the node_modules folder. 

https://github.com/SonofNun15/typescript-library-test

The setup is pretty simple. A tiny TypeScript project is compiled and "deployed" as an npm package. Another small app installs this library as a dependency via npm and then tries to import using either the commonjs or ES6 syntax. Results in the following error:

```
ERROR in ./source/app.ts
Module not found: Error: Cannot resolve module 'library' in /Users/josh/Dev/ts-libraries/consumer/source
 @ ./source/app.ts 1:16-34
```
Perhaps I'm missing something obvious?

**Comment by jbrantly** [comment]
Thanks, I'll take a look.

**Comment by jbrantly** [comment]
So the issue actually had nothing to do with ts-loader, and a little bit to do with webpack. In your webpack config you have this:

```
	resolve: {
		extensions: ['.js', '.ts'],
	},
```

The problem is that this *overwrites* the defaults which also includes an empty string (so that something like `require('somefile.json')` can resolve to `somefile.json` and not `somefile.json.js`. In any case, re-adding the empty string fixes the issue:

```
	resolve: {
		extensions: ['', '.js', '.ts'],
	},
```

See [here](http://webpack.github.io/docs/configuration.html#resolve-extensions) for the list of default extensions.

**Comment by SonofNun15** [comment]
I'm really glad it was this simple. Thanks so much for clearing this up!

**Comment by jbrantly** [comment]
NP! :grin:
